baseURL = "https://clement-rebuffel.com"
languageCode = "en-us"
title = "Clément Rebuffel"
enableEmoji = "true"
assetDir = "static"

[markup.goldmark.renderer]
    unsafe = true

[params]
    author = "Clément Rebuffel"
    avatar = "/images/profile-picture.png"
    shortdescription = "PhD Student in NLG"
    longdescription = [["Made in France", ":fr:"], ["Data-to-Text Generation", ""], ["Deep Learning aficionado", ""]]

    metadescription = "Personal website of Clément Rebuffel. I'm a 3rd year PhD student in Natural Language Generation"
    
    location = "France"

    email = "clement.rebuffel@protonmail.com"
    github = "https://github.com/KaijuML"
    twitter = "https://twitter.com/ClementRebuffel"
    linkedin = "https://fr.linkedin.com/in/clementrebuffel"
    scholar = "https://scholar.google.com/citations?user=QxRGjEUAAAAJ&hl=en"
