baseURL = "https://clement-rebuffel.com"
title = "Clément Rebuffel"

defaultContentLanguage = 'en'
languageCode = "en"

enableEmoji = "true"
assetDir = "static"

# This is necessary due to a bug (?) in how Hugo stores its sites
# See: https://discourse.gohugo.io/t/multilingual-page-404-not-found/31729/3
publishDir = "docs"

# This is not necessary, but removes some warnings as well
# as removes "tags" from the site map
disableKinds = ["taxonomyTerm"]

# This anables for rendering arbitrary html in markdown files.
[markup.goldmark.renderer]
    unsafe = true

[languages]
  [languages.en]
    weight = 2
    LanguageName = "English"
    shortdescription = "Quant Researcher at G-Research"

  [languages.fr]
    weight = 1
    LanguageName = "Français"
    shortdescription = "Quant Researcher chez G-Research"




[params]
    author = "Clément Rebuffel"
    avatar = "/images/avatar.jpeg"
    favicon = "/images/favicon.png"
    longdescription = [["Made in France", ":fr:"], ["Deep Learning aficionado", ""], ["Natural Language Processing", ":books:"]]

    metadescription = "Personal website of Clément Rebuffel. I'm a Quant Researcher at G-Research and PhD in Natural Language Generation"
    
    location = "London, UK"

    email = "clement.rebuffel@protonmail.com"
    github = "https://github.com/KaijuML"
    twitter = "https://twitter.com/ClementRebuffel"
    linkedin = "https://fr.linkedin.com/in/clementrebuffel"
    scholar = "https://scholar.google.com/citations?user=QxRGjEUAAAAJ&hl=en"
